spring:
  datasource:
    url: jdbc:mysql://${DB_LINK}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
  batch:
    job:
      name: ${JOB_NAME}
      enabled: true
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: false
        highlight_sql: false
        show_sql: false
        format_sql: false
        jdbc:
          batch_size: 30
        order_updates: true
        order_inserts: true

  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
#logging:
#  level:
#    org.hibernate.orm.jdbc.bind: trace

payment:
  kakao:
    secret:
      key: ${PAYMENT_KAKAO_SECRET_KEY}
    cid: ${PAYMENT_KAKAO_CID}

slack:
  token: ${SLACK_TOKEN}
